version: '3'

services:
    postgres:
        restart: always
        image: postgres:latest
        container_name: postgres
        # environment:
        #     POSTGRES_PASSWORD: password
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data:/var/lib/postgresql/data
        networks:
          - aiohttp

    {{cookiecutter.app_name}}:
        restart: always
        build:
            context: .
        ports:
            - "{{cookiecutter.server_port}}:{{cookiecutter.server_port}}"
        env_file: .env
        environment:
            AIOHTTP_DB_HOST: postgres
            AIOHTTP_DB_DATABASE: postgres
            # AIOHTTP_DB_PASSWORD: password
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - aiohttp

volumes:
    /var/lib/postgresql/data:
        driver: local

networks:
    aiohttp:
